name: spllive
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 2.0.3+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_screenutil: ^5.9.3
  get: ^4.7.2
  http: ^1.3.0
  get_storage: ^2.1.1
  carousel_slider: ^5.0.0
  connectivity_plus: ^6.1.3
  flutter_svg: ^2.0.17
  #  country_list_pick: ^1.0.1+6
  pin_code_fields: ^8.0.1
  device_info_plus: ^11.3.0
  package_info_plus: ^8.2.1
  intl: ^0.20.2
  cached_network_image: ^3.4.1
  flutter_rating_bar: ^4.0.1
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  image_picker: ^1.1.2
  flutter_pin_code_fields: ^2.2.0
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^15.2.3
  firebase_core: ^3.12.0
  #  geolocator: ^10.0.1
  #  geocoding: ^2.1.0
  #  flutter_jailbreak_detection: ^1.10.0
  unique_identifier: ^0.4.0
#  in_app_update: ^4.2.3
#  upgrader: ^11.3.1
  ota_update: ^7.0.1
  permission_handler: ^11.4.0

  dio: ^5.8.0+1
  path_provider: ^2.1.5
  firebase_remote_config: ^5.4.2

#  open_filex: ^4.6.0
#  android_intent_plus: ^5.3.0
#  colorful_safe_area: ^1.0.0



dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - assets/JSON File/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto_slab/RobotoSlab-Bold.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-Medium.ttf
        - asset: assets/fonts/roboto_slab/RobotoSlab-Regular.ttf
    - family: PTsans
      fonts:
        - asset: assets/fonts/pt_sans/PTSans-Bold.ttf
        - asset: assets/fonts/pt_sans/PTSans-Regular.ttf
    - family: RobotoSans
      fonts:
        - asset: assets/fonts/roboto_sans/Roboto-Bold.ttf
        - asset: assets/fonts/roboto_sans/Roboto-Medium.ttf
        - asset: assets/fonts/roboto_sans/Roboto-Regular.ttf
    - family: Allerta
      fonts:
        - asset: assets/fonts/Allerta/Allerta-Regular.ttf
    - family: Rambla
      fonts:
        - asset: assets/fonts/rambla/Rambla-Bold.ttf
    - family: Gotham
      fonts:
        - asset: assets/fonts/Gotham/GothamBold.ttf
        - asset: assets/fonts/Gotham/GothamMedium.ttf
        - asset: assets/fonts/Gotham/GothamLight.ttf
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter/inter_regular.ttf

  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

